### ISSUE TITLE
[Bug]: Unable to fetch and download the stories, try again! (Instagram stories section)

### ISSUE THREAD

**Issue by NomanBaigA** [ashutoshkrris/EazyLoader#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

I tried different celeb names there but it's not able to fetch their stories.
after loading, it gives the error.

### Expected Behavior

It should work with stories also because everything works perfectly except this

### To Reproduce

I am new to web

### Anything else?

Thanks ;) for this amazing work

### Hacktoberfest

- [ ] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutoshkrris** [comment]
Hi @NomanBaigA 
Thanks for pointing out the bug.
It has been resolved now. Hoping that it works for you!
If you'd like to support us, checkout [this page](https://eazyloader.herokuapp.com/donate)

**Comment by NomanBaigA** [comment]
> Hi @NomanBaigA Thanks for pointing out the bug. It has been resolved now. Hoping that it works for you! If you'd like to support us, checkout [this page](https://eazyloader.herokuapp.com/donate)

still not working. I am trying it with this link https://eazyloader.herokuapp.com/
and got a new error after loading -

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail


am I trying it in the wrong way

**Comment by ashutoshkrris** [comment]
@NomanBaigA 
The app is working fine at our end.
